using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[RequireComponent(typeof(Renderer))]
public class PixelateController : MonoBehaviour
{
    Material _material;

    // This property name is generated by ShaderGraph, in order to set it in the material you need to put the .ShaderGraph in Debug mode.
    // In "Parsed Form -> Prop Info -> Props and find the corresponding property.
    string _resolution_property_name = "Vector1_47CCBCA7";

    void Start ()
    {
        Renderer renderer = GetComponent<Renderer>();
        _material = renderer.sharedMaterial;
    }
	
    void Update ()
    {
        var s = (Mathf.Sin(Time.time * 1.25f) + 1.0f) / 2.0f;
        var r = Mathf.Lerp(32, 512, s);
        _material.SetFloat(_resolution_property_name, r);
    }
}
